---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "webshell.labels" . | nindent 4 }}
type: Opaque
data:
{{ if eq .Values.ingress.className "haproxy"}}
  {{ .Values.user }}: {{ .Values.password | b64enc | quote }}
{{ else }}
  auth: {{ (htpasswd .Values.user .Values.password) | b64enc | quote }}
{{ end }}