# to be used for devoping on hetzner cluster

user: "mystudent" # This should be the namespace where the student's webshell is deployed to
password: "supersecretbassword" # For the basic-auth Autentication

ingress: # Make sure this fits your environment!
  enabled: true
  className: "haproxy"
  hosts:
    - host: mystudent.training.cluster.songlaa.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - hosts:
       - mystudent.training.cluster.songlaa.com

theia:
  persistence:
    storageclass: longhorn
    enabled: true
dind:
  persistence:
    storageclass: longhorn
    pvcsize: 50Gi
    enabled: true